version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - unused
    - sloglint

  settings:
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - []
            - - skipPackageNameChecks: true
    sloglint:
      msg-style: lowercased
